version: '3'

services:
  app:
    container_name: Adopet-challenge
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    networks:
      - adopet-challenge
    environment:
      - PORT=${PORT}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    ports:
      - ${PORT}:${PORT}

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - adopet-challenge

  adminer:
    image: adminer
    container_name: adminer
    networks:
      - adopet-challenge
    restart: always
    ports:
      - 8000:8080

networks:
    adopet-challenge:
      driver: bridge

volumes:
  postgres-data:
